# Generated by Django 5.1.6 on 2025-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkd_online_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bd',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.CharField(max_length=30, null=True, verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Регион'),
        ),
    ]
