# Generated by Django 5.1.6 on 2025-03-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkd_online_forum', '0002_alter_user_bd_alter_user_club_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Новостной тег',
                'verbose_name_plural': 'Новостные теги',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('about', models.CharField(max_length=500, verbose_name='Описание')),
                ('banner', models.FileField(blank=True, null=True, upload_to='news/', verbose_name='Баннер')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tkd_online_forum.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
