# Generated by Django 5.1.6 on 2025-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkd_online_forum', '0004_news_active_news_cost_news_date_begin_news_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='event_banners/', verbose_name='Баннер'),
        ),
    ]
