# Generated by Django 5.1.6 on 2025-03-31 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkd_online_forum', '0005_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео'),
        ),
    ]
